#pragma config(Sensor, in1,    topLiftPoten,   sensorPotentiometer)
#pragma config(Sensor, in2,    baseLiftPoten,  sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  forkliftButton, sensorDigitalIn)
#pragma config(Sensor, dgtl8,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, leftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           topLiftLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           topLiftRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveMotorsLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveMotorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           baseLiftLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileLiftLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mobileLiftRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseLiftRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//NOTE: dgt3 and/or dgt4 do not work

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "\InTheZoneLibrary.c"

void pre_auton()
{
	SensorValue[redLED] = 1;
	writeDebugStreamLine("begin gyro init");
	SensorType[in4] = sensorNone;
	wait1Msec(1000);
	SensorType[in4] = sensorGyro;
	wait1Msec(2000);
	SensorScale[in4] = 137;
	writeDebugStreamLine("finished gyro init %d", SensorScale[in4]);
	SensorValue[redLED] = 0;
	SensorValue[greenLED] = 1;
	//white line -- -1315


}
void runBasicCompAuton(string majorSide, int minorSide, int zone)
{
	//minorSide: 1 = left, -1 = right, majorSide parameter not used yet
	clearTimer(T1);
	reachedMobileGoal = false; //will act as hard stop for lifting cone â?? when reachedMobileGoal is true, the lift will immediately drop

	//Go to mobile goal â Drop mobile base lift, lift cone, and drive straight
	setBaseLiftPos(3900, 10);
	setForkliftPos(FORKLIFT_DOWN);
	//setTopLiftPos(BACK_TOP,7,-15);  //UNCOMMENT ONCE POTEN IS ON LIFT
	driveStraight(1600,127); //drive to mobile goal

	//pick up goal
	reachedMobileGoal = true; //force cone lift to drop
	//setForkliftPower(1); //pick up goal
		setForkliftPos(FORKLIFT_UP);
	//setTopLiftPos(SCORE_TOP + 150, 7, -15); //+300 quick fix for wrong enum after pot swap //UNCOMMENT AFTER FIX
	wait1Msec(300);

	//drive back
	turnToPos(0);
	driveStraight(-1200,127); //drive back -1000
	setClawPower(-127);
	wait1Msec(300);
	setClawPower(0);

	//Score goal
	if(zone == 5)
	{
		//just turn around and drive straight
		turnToPos(-1800*minorSide);
		driveStraight(400,127);
	}
	else if(zone == 10)
	{
		//turn roughly parallel to white line, drive forward a bit, turn fully to face 10 pt zone, then drive straight
		turnToPos(-1315*minorSide);
		driveStraight(400,127);
		//turnDeg(250);
		turnToPos(-2245*minorSide);
		driveStraight(700,127);
	}
	else if(zone == 20)
	{
		//turn roughly parallel to white line, drive forward a bit, turn fully to face 10 pt zone, then drive straight
		turnToPos(-1315*minorSide);
		driveStraight(400,127);
		//turnDeg(250);
		turnToPos(-2245*minorSide);
		driveStraight(700,127);
	}
	//setClawPower(-127);
	//wait1Msec(250);
	//setTopLiftPos(3100,7,-15);
	//wait1Msec(150);
	//wait1Msec(250);

	//Score cone and back away
	setClawPower(127);
	//moved earlier
	setBaseLiftPos(3850, 7); //lift up cone â?? possibly change this to not go back all the way (potentially wasting time in driver control)
		setForkliftPos(FORKLIFT_DOWN);
	wait1Msec(500);
	setClawPower(0);
	driveStraight(-800,127,1);
	wait1Msec(250);
	setTopLiftPower(0);
	writeDebugStreamLine("Time: %d", time1(T1));
}

void runProgSkills()
{
	//run auton to score in 20Z
		string blank = "";
		runBasicCompAuton(blank,1,20);
	//reset to left?
			//run low power forward?
			//turn w/ gyro to back into left wall
			//back into wall
	//drive to near left corner and score in 10Z left
			//drive to correct spot to align with goal
			//turn w/ gyro
			//drive forward and pick up goal
			//turn 180 to face scoring spot
			//drive forward
			//score 10Z
	//drive to near right corner and score in 10Z right
			//turn
			//drive forward until aligned
			//turn
			//drive forward and pick up goal
			//turn 180 to face scoring spot
			//drive forward
			//score 10Z
	//drive to far right corner and score in 10Z middle
			//turn 180
			//drive forward and pick up goal
			//turn 180
			//drive forward until 5Z
			//turn
			//drive
			//turn to center
			//score goal in 10Z
	//drive to far left corner and score in far 20Z
			//turn to left
			//drive until aligned
			//turn until aligned
			//drive forward and pick up goal
			//drive forward
			//turn
			//drive
			//turn to 20Z
			//score in 20Z
}

task autonomous()
{
	string majorSide = "blue";
	int minorSide = 1; //1 = left, -1 = right
	int zone = 10; //choose 5 or 10
	runBasicCompAuton(majorSide,minorSide,zone);
	//runProgSkills(side);
}
void testSpeedStuff()
{
	setTopLiftPos(SCORE_TOP,SCORE_KP_TOP);
	setBaseLiftPower(-127);
	while(SensorValue[topLiftPoten] < SCORE_TOP){wait1Msec(20);}
	setBaseLiftPower(0);
	float baseChange = 4095 - SensorValue[baseLiftPoten];
	float topChange = SensorValue[topLiftPoten];
	writeDebugStreamLine("BasePoten per Top Poten: %d", baseChange/topChange);
}

task usercontrol()
{
	bool coneUpPressed = false;
	bool coneDownPressed = false;
	bool coneZeroPressed = false;
	bool centerPushed = false; //Center piston pushed or naw
	bool autoStackPressed = false;

	while(true)
	{
		if(vexRT[Btn7L]==1)
		{
			string side = "blue";
			testSpeedStuff();
			//runBasicCompAuton(side,1,5);
			writeDebugStreamLine("Running basic comp auton");
		}
		//if(vexRT[Btn7R]==1)
		//{
		//	string side = "blue";
		//	runProgSkills();
		//}

		//Buttons and Joysticks
		int  rightJoy = vexRT[Ch2];
		int  leftJoy = vexRT[Ch3];
		word rightTriggerUp = vexRT[Btn6U]; //for score top lift
		word rightTriggerDown = vexRT[Btn6D]; //for back top lift
		word leftTriggerUp = vexRT[Btn5U]; //for pincer close
		word leftTriggerDown = vexRT[Btn5D]; //for pincer open
		word btnEightUp = vexRT[Btn8U]; //for up base lift
		word btnEightDown = vexRT[Btn8D]; //for down base lift
		word btnSevenUp = vexRT[Btn7U]; //forklift up
		word btnSevenDown = vexRT[Btn7D]; //forklift down
		word btnEightLeft = vexRT[Btn8L]; //auto score
		word btnEightRight = vexRT[Btn8R]; //auto back
		word btnSevenLeft = vexRT[Btn7L]; //no more auton testing, move to matchloads
		word secondBtnSevenUp = vexRT[Btn7UXmtr2]; //+1 to cone count
		word secondBtnSevenDown = vexRT[Btn7DXmtr2]; //-1 to cone count
		word secondBtnSevenLeft = vexRT[Btn7LXmtr2]; //zero cone count

		//Drive Motors
		if(fabs(rightJoy) >= 15)
			setRightMotors(rightJoy);
		else
			setRightMotors(0);

		if(fabs(leftJoy) >= 15)
			setLeftMotors(leftJoy);
		else
			setLeftMotors(0);


		//TOP LIFT
		if(rightTriggerUp == 1)
		{
			//setTopLiftPower(127);
			setTopLiftPos(SCORE_TOP,SCORE_KP_TOP);
		}
		else if(rightTriggerDown == 1)
		{
			//setTopLiftPower(-80);
			setTopLiftPos(BACK_TOP,BACK_KP_TOP);
		}
		//else
		//{
		//	setTopLiftPower(0);
		//}

		//BASE LIFT
		if(btnEightUp == 1)
		{
			writeDebugStreamLine("%d",userControlBase);
			if(userControlBase)
				setBaseLiftPower(-127);
			else
				userControlBase = true;
		}
		else if(btnEightDown == 1)
		{
			if(userControlBase)
				setBaseLiftPower(80);
			else
				userControlBase = true;
		}
		else
		{
			if(userControlBase)
				setBaseLiftPower(0);
		}

		//Mobile Goal Base Lifters
		if(btnSevenUp == 1)
		{
			if(SensorValue(forkliftButton) == 1)
				setForkliftPower(127);
			else
				setForkliftPower(0);
		}
		else if(btnSevenDown == 1)
			setForkliftPower(-127);
		else
			setForkliftPower(0);


		//claw
		if(leftTriggerDown == 1)
		{
			if(userControlClaw)
				setClawPower(110); //open claw
			else
				userControlClaw = true;
		}
		else if(leftTriggerUp == 1)
		{
			if(userControlClaw)
				setClawPower(-110); //close claw
			else
				userControlClaw = true;
		}
		else
		{
			if(userControlClaw)
				setClawPower(0);
		}

		//AUTO METHODS
        if(btnEightLeft == 1){autoBack();}
        else if(btnEightRight == 1 && !autoStackPressed) //if button is now pressed, update cones and update bool to reflect button pressed
        {
            autoStackPressed = true;
            autoStack();
            writeDebugStreamLine("Cones Stacked: %d", conesStacked);
        }
        else if(btnEightRight == 0 && autoStackPressed) //if button is no longer pressed, update bool to reflect lack of press
        {
            autoStackPressed = false;
        }


		//if(btnSevenLeft == 1)
		//{
		//	setBaseLiftPos(MATCHLOAD_BASE,MATCHLOAD_KP_BASE);
		//	setTopLiftPos(MATCHLOAD_TOP,MATCHLOAD_KP_TOP);
		//}

		//cone count
		if(secondBtnSevenUp == 1 && !coneUpPressed) //if button is now pressed, update cones and update bool to reflect button pressed
		{
			conesStacked++;
			coneUpPressed = true;
		}
		else if(secondBtnSevenUp == 0 && coneUpPressed) //if button is no longer pressed, update bool to reflect lack of press
		{
			coneUpPressed = false;
		}

		if(secondBtnSevenDown == 1 && !coneDownPressed) //if button is now pressed, update cones and update bool to reflect button pressed
		{
			conesStacked--;
			coneDownPressed = true;
		}
		else if(secondBtnSevenDown == 0 && coneDownPressed) //if button is no longer pressed, update bool to reflect lack of press
		{
			coneDownPressed = false;
		}

		if(secondBtnSevenLeft == 1 && !coneZeroPressed) //if button is now pressed, update cones and update bool to reflect button pressed
		{
			conesStacked = 0;
			coneZeroPressed = true;
		}
		else if(secondBtnSevenLeft == 0 && coneZeroPressed) //if button is no longer pressed, update bool to reflect lack of press
		{
			coneZeroPressed = false;
		}
	}
}
